databases:
  - name: recruiter-ai-db
    plan: free

services:
  - type: web
    name: recruiter-ai
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py ensure_superuser"
    startCommand: "gunicorn config.wsgi:application --timeout 300 --workers 2"
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.9"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: GEMINI_API_KEY
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: recruiter-ai-db
          property: connectionString
