# Generated by Django 6.0.6 on 2026-07-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_file", models.FileField(upload_to="resumes/%Y/%m/")),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                (
                    "current_job_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("professional_summary", models.TextField(blank=True, null=True)),
                (
                    "highest_degree",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("university", models.CharField(blank=True, max_length=255, null=True)),
                ("graduation_year", models.IntegerField(blank=True, null=True)),
                ("experiences", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("projects", models.JSONField(blank=True, default=list)),
                ("candidate_summary", models.TextField(blank=True, null=True)),
                ("total_experience_years", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("hired", "Hired"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
