# Generated by Django 6.0.6 on 2026-07-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="gpa",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
