# Generated by Django 6.0.6 on 2026-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_candidate_file_hash_candidate_gpa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="total_experience_years",
        ),
        migrations.AddField(
            model_name="candidate",
            name="total_experience_months",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
