# Generated by Django 6.0.6 on 2026-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_remove_candidate_total_experience_years_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="source",
            field=models.CharField(
                choices=[("internal", "HR Upload"), ("public", "Careers Page")],
                default="internal",
                max_length=20,
            ),
        ),
    ]
